import ThemeWrapper from "./ThemeWrapper";
import CustomDashboard from "./custom/Dashboard";

export default function Layout({ children }: any) {

  return (
    <ThemeWrapper>
      {/*<Head>*/}
      {/*  <title>Create Next App</title>*/}
      {/*  <meta name="description" content="Generated by create next app"/>*/}
      {/*  <link rel="icon" href="/favicon.ico"/>*/}
      {/*</Head>*/}

      <CustomDashboard>
        {children}
      </CustomDashboard>
    </ThemeWrapper>
  );
}
